// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1p4NBeUKd0nSm6eIP-MONlr34h8aVmBA',
    appId: '1:482308073899:web:2e071528a16ed910694aee',
    messagingSenderId: '482308073899',
    projectId: 'fruitecommerce-20c5c',
    authDomain: 'fruitecommerce-20c5c.firebaseapp.com',
    storageBucket: 'fruitecommerce-20c5c.firebasestorage.app',
    measurementId: 'G-26ZB250K46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMNEY7Hq-VISsYHrX7NDyFxRTW8Voqng',
    appId: '1:482308073899:android:6036d47597dd103a694aee',
    messagingSenderId: '482308073899',
    projectId: 'fruitecommerce-20c5c',
    storageBucket: 'fruitecommerce-20c5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK_NJgf_8kkYyLQx-pTuWnbKHKYhaZMRc',
    appId: '1:482308073899:ios:12536ab41eac38a4694aee',
    messagingSenderId: '482308073899',
    projectId: 'fruitecommerce-20c5c',
    storageBucket: 'fruitecommerce-20c5c.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK_NJgf_8kkYyLQx-pTuWnbKHKYhaZMRc',
    appId: '1:482308073899:ios:12536ab41eac38a4694aee',
    messagingSenderId: '482308073899',
    projectId: 'fruitecommerce-20c5c',
    storageBucket: 'fruitecommerce-20c5c.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1p4NBeUKd0nSm6eIP-MONlr34h8aVmBA',
    appId: '1:482308073899:web:ab58c3dee69d2030694aee',
    messagingSenderId: '482308073899',
    projectId: 'fruitecommerce-20c5c',
    authDomain: 'fruitecommerce-20c5c.firebaseapp.com',
    storageBucket: 'fruitecommerce-20c5c.firebasestorage.app',
    measurementId: 'G-P48Q2HZXTV',
  );
}
